[package]
name = "test-processing"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
math = { package = "lib-math", path = "../lib-math" }
processing = { package = "lib-processing", path = "../lib-processing", features = ["debug", "csv"] }
